### ISSUE TITLE
Expose `HashDict.size`, `HashSet.size`

### ISSUE THREAD

**Issue by mitchellwrosen** [nikita-volkov/hashing-containers#1]
Would be great to have these functions :+1:

**Comment by nikita-volkov** [comment]
Unfortunately, until they expose a function, which would let us update and return a value in one op, in the API of IntDict, implementing such functionality would come with a large overhead for all modifying ops.

Until we have this functionality of IntDict, the only way to count the amount of elements is by iterating thru each element. Since such operation has a complexity of O(n), exposing it would indulge the users to make wrong assumptions. It's still possible to count the amount of elements thru the `foldl` function, which also makes the complexity clear.

**Comment by mitchellwrosen** [comment]
Understood. I don't think it's wrong to export an `O(n)` size function (`unordered-containers` does it). But I'm happy just to `foldl` as well :)

**Comment by nikita-volkov** [comment]
Alright. I've just released it :)
